name: build image
on:
  push:
    branches: [ web ]

permissions:
  contents: read
  packages: write

jobs:
  builds: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout del codigo
        uses: actions/checkout@v5

      - name: login a github packages
        uses: docker/login-action@v2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: convertir nombre de propietario a minÃºsculas
        id: vars
        run: echo "owner_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Construir y publicar la imagen docker
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: ghcr.io/${{ env.owner_lower }}/web_app:latest